package com.cloud.web.arena;

import org.springframework.stereotype.Repository;
import web.account.AccountDatabase;

import javax.annotation.PostConstruct;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

@Repository
public class ArenaRepository {
    private final AccountDatabase db;
    public ArenaRepository(AccountDatabase db){this.db=db;}
    @PostConstruct public void init(){try(Connection c=db.getConnection();Statement s=c.createStatement()){
        s.execute("CREATE TABLE IF NOT EXISTS arena_player(user_id INTEGER PRIMARY KEY,liquid INTEGER NOT NULL DEFAULT 5000,coins INTEGER NOT NULL DEFAULT 2500,fate INTEGER NOT NULL DEFAULT 12,stones INTEGER NOT NULL DEFAULT 800,pity INTEGER NOT NULL DEFAULT 0,dungeon_cleared INTEGER NOT NULL DEFAULT 0,dungeon_attempts INTEGER NOT NULL DEFAULT 5,formation_level INTEGER NOT NULL DEFAULT 1,grotto_level INTEGER NOT NULL DEFAULT 1,grotto_claim_at INTEGER NOT NULL DEFAULT 0,task_day TEXT NOT NULL DEFAULT '',task_login INTEGER NOT NULL DEFAULT 0,task_dungeon INTEGER NOT NULL DEFAULT 0,task_rank INTEGER NOT NULL DEFAULT 0,task_recruit INTEGER NOT NULL DEFAULT 0,task_arena INTEGER NOT NULL DEFAULT 0,claimed TEXT NOT NULL DEFAULT '')");
        s.execute("CREATE TABLE IF NOT EXISTS arena_hero(user_id INTEGER NOT NULL,hero_id TEXT NOT NULL,rank INTEGER NOT NULL DEFAULT 1,stars INTEGER NOT NULL DEFAULT 1,skill_level INTEGER NOT NULL DEFAULT 1,shards INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(user_id,hero_id))");
        s.execute("CREATE TABLE IF NOT EXISTS arena_draw_log(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,hero_id TEXT NOT NULL,quality TEXT NOT NULL,duplicate INTEGER NOT NULL,created_at INTEGER NOT NULL)");
    }catch(SQLException e){throw new IllegalStateException("初始化剑气 SQLite 表失败",e);}}
    public synchronized Map<String,Object> state(long uid)throws SQLException{try(Connection c=db.getConnection()){c.setAutoCommit(false);ensure(c,uid);refresh(c,uid);Map<String,Object> out=read(c,uid);c.commit();return out;}}
    public synchronized Map<String,Object> action(long uid,String action,String id,int count,long now)throws SQLException{try(Connection c=db.getConnection()){c.setAutoCommit(false);ensure(c,uid);refresh(c,uid);switch(action){
        case "rank": rank(c,uid,id,false);break;case "skill":rank(c,uid,id,true);break;case "dungeon":dungeon(c,uid,count);break;case "draw":draw(c,uid,count,now);break;case "claim":claim(c,uid,id);break;case "formation":spend(c,uid,"stones","formation_level",100);break;case "grotto":grotto(c,uid,now);break;case "arena":progress(c,uid,"task_arena",1);break;default:throw new IllegalArgumentException("未知操作");}Map<String,Object> out=read(c,uid);c.commit();return out;}}
    private void ensure(Connection c,long u)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO arena_player(user_id) VALUES(?)")){p.setLong(1,u);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO arena_hero(user_id,hero_id) VALUES(?,?)")){for(String h:new String[]{"jianhuang","leizun"}){p.setLong(1,u);p.setString(2,h);p.addBatch();}p.executeBatch();}}
    private void refresh(Connection c,long u)throws SQLException{String d=LocalDate.now().toString();try(PreparedStatement p=c.prepareStatement("UPDATE arena_player SET task_day=?,dungeon_attempts=5,task_login=1,task_dungeon=0,task_rank=0,task_recruit=0,task_arena=0,claimed='' WHERE user_id=? AND task_day<>?")){p.setString(1,d);p.setLong(2,u);p.setString(3,d);p.executeUpdate();}}
    private void rank(Connection c,long u,String h,boolean skill)throws SQLException{String col=skill?"skill_level":"rank",money=skill?"coins":"liquid";int unit=skill?150:200;int level;try(PreparedStatement p=c.prepareStatement("SELECT "+col+" FROM arena_hero WHERE user_id=? AND hero_id=?")){p.setLong(1,u);p.setString(2,h);try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalArgumentException("尚未拥有该仙侣");level=r.getInt(1);}}spendAmount(c,u,money,(long)level*unit);try(PreparedStatement p=c.prepareStatement("UPDATE arena_hero SET "+col+"="+col+"+1 WHERE user_id=? AND hero_id=?")){p.setLong(1,u);p.setString(2,h);p.executeUpdate();}progress(c,u,"task_rank",1);}
    private void dungeon(Connection c,long u,int stage)throws SQLException{int cleared,tries;try(PreparedStatement p=c.prepareStatement("SELECT dungeon_cleared,dungeon_attempts FROM arena_player WHERE user_id=?")){p.setLong(1,u);try(ResultSet r=p.executeQuery()){r.next();cleared=r.getInt(1);tries=r.getInt(2);}}if(stage<1||stage>12||stage>cleared+1)throw new IllegalArgumentException("请先通关前置副本");if(tries<1)throw new IllegalArgumentException("今日副本次数已用完");boolean first=stage>cleared;try(PreparedStatement p=c.prepareStatement("UPDATE arena_player SET dungeon_attempts=dungeon_attempts-1,dungeon_cleared=max(dungeon_cleared,?),liquid=liquid+?,coins=coins+? WHERE user_id=?")){p.setInt(1,stage);p.setLong(2,(first?600:180)*stage);p.setLong(3,(first?120:40)*stage);p.setLong(4,u);p.executeUpdate();}progress(c,u,"task_dungeon",1);}
    private void draw(Connection c,long u,int n,long seed)throws SQLException{if(n!=1&&n!=10)throw new IllegalArgumentException("只支持单抽或十连");spendAmount(c,u,"fate",n);int pity;try(PreparedStatement p=c.prepareStatement("SELECT pity FROM arena_player WHERE user_id=?")){p.setLong(1,u);try(ResultSet r=p.executeQuery()){r.next();pity=r.getInt(1);}}String[] ids={"qinglan","xuanshuang","chixiao","taixu","yaohuang","leizun","jianhuang"};Random rng=new Random(seed);for(int i=0;i<n;i++){pity++;String q=pity>=90?"金":rng.nextInt(100)<2?"金":rng.nextInt(100)<20?"红":"橙";if(n==10&&i==9&&q.equals("橙"))q="红";if(q.equals("金"))pity=0;String h=ids[rng.nextInt(ids.length)];boolean dup=owned(c,u,h);if(dup){try(PreparedStatement p=c.prepareStatement("UPDATE arena_hero SET shards=shards+? WHERE user_id=? AND hero_id=?")){p.setInt(1,q.equals("金")?80:q.equals("红")?40:20);p.setLong(2,u);p.setString(3,h);p.executeUpdate();}}else try(PreparedStatement p=c.prepareStatement("INSERT INTO arena_hero(user_id,hero_id) VALUES(?,?)")){p.setLong(1,u);p.setString(2,h);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT INTO arena_draw_log(user_id,hero_id,quality,duplicate,created_at) VALUES(?,?,?,?,?)")){p.setLong(1,u);p.setString(2,h);p.setString(3,q);p.setInt(4,dup?1:0);p.setLong(5,System.currentTimeMillis());p.executeUpdate();}}try(PreparedStatement p=c.prepareStatement("UPDATE arena_player SET pity=? WHERE user_id=?")){p.setInt(1,pity);p.setLong(2,u);p.executeUpdate();}progress(c,u,"task_recruit",n);}
    private void claim(Connection c,long u,String id)throws SQLException{Map<String,int[]> cfg=new HashMap<>();cfg.put("login",new int[]{1,200,0,0});cfg.put("dungeon",new int[]{3,500,0,0});cfg.put("rank",new int[]{1,0,300,0});cfg.put("recruit",new int[]{1,0,0,1});cfg.put("arena",new int[]{1,0,400,0});int[] x=cfg.get(id);if(x==null)throw new IllegalArgumentException("未知任务");String claimed, col="task_"+id;int progress;try(PreparedStatement p=c.prepareStatement("SELECT "+col+",claimed FROM arena_player WHERE user_id=?")){p.setLong(1,u);try(ResultSet r=p.executeQuery()){r.next();progress=r.getInt(1);claimed=r.getString(2);}}if(Arrays.asList(claimed.split(",")).contains(id))throw new IllegalArgumentException("奖励已领取");if(progress<x[0])throw new IllegalArgumentException("任务未完成");try(PreparedStatement p=c.prepareStatement("UPDATE arena_player SET liquid=liquid+?,coins=coins+?,fate=fate+?,claimed=claimed||? WHERE user_id=?")){p.setInt(1,x[1]);p.setInt(2,x[2]);p.setInt(3,x[3]);p.setString(4,id+",");p.setLong(5,u);p.executeUpdate();}}
    private void grotto(Connection c,long u,long now)throws SQLException{long last;int lv;try(PreparedStatement p=c.prepareStatement("SELECT grotto_claim_at,grotto_level FROM arena_player WHERE user_id=?")){p.setLong(1,u);try(ResultSet r=p.executeQuery()){r.next();last=r.getLong(1);lv=r.getInt(2);}}long hours=last==0?4:Math.max(1,Math.min(12,(now-last)/3600000));try(PreparedStatement p=c.prepareStatement("UPDATE arena_player SET liquid=liquid+?,grotto_claim_at=? WHERE user_id=?")){p.setLong(1,hours*240*lv);p.setLong(2,now);p.setLong(3,u);p.executeUpdate();}}
    private void spend(Connection c,long u,String money,String level,int unit)throws SQLException{int lv;try(PreparedStatement p=c.prepareStatement("SELECT "+level+" FROM arena_player WHERE user_id=?")){p.setLong(1,u);try(ResultSet r=p.executeQuery()){r.next();lv=r.getInt(1);}}spendAmount(c,u,money,(long)lv*unit);try(PreparedStatement p=c.prepareStatement("UPDATE arena_player SET "+level+"="+level+"+1 WHERE user_id=?")){p.setLong(1,u);p.executeUpdate();}}
    private void spendAmount(Connection c,long u,String col,long amount)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE arena_player SET "+col+"="+col+"-? WHERE user_id=? AND "+col+">=?")){p.setLong(1,amount);p.setLong(2,u);p.setLong(3,amount);if(p.executeUpdate()!=1)throw new IllegalArgumentException("资源不足");}}
    private void progress(Connection c,long u,String col,int n)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE arena_player SET "+col+"="+col+"+? WHERE user_id=?")){p.setInt(1,n);p.setLong(2,u);p.executeUpdate();}}
    private boolean owned(Connection c,long u,String h)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT 1 FROM arena_hero WHERE user_id=? AND hero_id=?")){p.setLong(1,u);p.setString(2,h);try(ResultSet r=p.executeQuery()){return r.next();}}}
    private Map<String,Object> read(Connection c,long u)throws SQLException{Map<String,Object> o=new LinkedHashMap<>();try(PreparedStatement p=c.prepareStatement("SELECT * FROM arena_player WHERE user_id=?")){p.setLong(1,u);try(ResultSet r=p.executeQuery()){r.next();for(String k:new String[]{"liquid","coins","fate","stones","pity","dungeon_cleared","dungeon_attempts","formation_level","grotto_level"})o.put(camel(k),r.getLong(k));String claimed=r.getString("claimed");Map<String,Object> tasks=new LinkedHashMap<>();for(String id:new String[]{"login","dungeon","rank","recruit","arena"}){Map<String,Object> t=new LinkedHashMap<>();t.put("progress",r.getInt("task_"+id));t.put("claimed",Arrays.asList(claimed.split(",")).contains(id));tasks.put(id,t);}o.put("tasks",tasks);}}List<Map<String,Object>> hs=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT * FROM arena_hero WHERE user_id=? ORDER BY hero_id")){p.setLong(1,u);try(ResultSet r=p.executeQuery()){while(r.next()){Map<String,Object> h=new LinkedHashMap<>();h.put("id",r.getString("hero_id"));h.put("rank",r.getInt("rank"));h.put("stars",r.getInt("stars"));h.put("skill",r.getInt("skill_level"));h.put("shards",r.getInt("shards"));hs.add(h);}}}o.put("heroes",hs);return o;}
    private String camel(String s){StringBuilder b=new StringBuilder();boolean up=false;for(char c:s.toCharArray())if(c=='_')up=true;else{b.append(up?Character.toUpperCase(c):c);up=false;}return b.toString();}
}
