id=10001
port=5500
center=127.0.0.1:5400
plant=0
game.score-db=../lobby/data/lobby.db
game.config-reload-seconds=30
game.web-offline-timeout-seconds=30
robot.operation-delay-min-ms=3000
robot.operation-delay-max-ms=6000
